#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.DataAccessLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="axosnet")]
	public partial class dalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDoctos(Doctos instance);
    partial void UpdateDoctos(Doctos instance);
    partial void DeleteDoctos(Doctos instance);
    partial void InsertMonedas(Monedas instance);
    partial void UpdateMonedas(Monedas instance);
    partial void DeleteMonedas(Monedas instance);
    partial void InsertProveedores(Proveedores instance);
    partial void UpdateProveedores(Proveedores instance);
    partial void DeleteProveedores(Proveedores instance);
    #endregion
		
		public dalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["axosnetConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Doctos> Doctos
		{
			get
			{
				return this.GetTable<Doctos>();
			}
		}
		
		public System.Data.Linq.Table<Monedas> Monedas
		{
			get
			{
				return this.GetTable<Monedas>();
			}
		}
		
		public System.Data.Linq.Table<Proveedores> Proveedores
		{
			get
			{
				return this.GetTable<Proveedores>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doctos")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Doctos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DoctoID;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private decimal _Monto;
		
		private int _ProveedorID;
		
		private int _MonedaID;
		
		private string _Comentario;
		
		private System.Nullable<System.DateTime> _FechaHoraCreacion;
		
		private System.Nullable<System.DateTime> _FechaHoraModificacion;
		
		private System.Guid _UsuarioID;
		
		private EntityRef<Monedas> _Monedas;
		
		private EntityRef<Proveedores> _Proveedores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDoctoIDChanging(int value);
    partial void OnDoctoIDChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnMontoChanging(decimal value);
    partial void OnMontoChanged();
    partial void OnProveedorIDChanging(int value);
    partial void OnProveedorIDChanged();
    partial void OnMonedaIDChanging(int value);
    partial void OnMonedaIDChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    partial void OnFechaHoraCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraCreacionChanged();
    partial void OnFechaHoraModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraModificacionChanged();
    partial void OnUsuarioIDChanging(System.Guid value);
    partial void OnUsuarioIDChanged();
    #endregion
		
		public Doctos()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoctoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int DoctoID
		{
			get
			{
				return this._DoctoID;
			}
			set
			{
				if ((this._DoctoID != value))
				{
					this.OnDoctoIDChanging(value);
					this.SendPropertyChanging();
					this._DoctoID = value;
					this.SendPropertyChanged("DoctoID");
					this.OnDoctoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Money NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this.OnMontoChanging(value);
					this.SendPropertyChanging();
					this._Monto = value;
					this.SendPropertyChanged("Monto");
					this.OnMontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProveedorID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public int ProveedorID
		{
			get
			{
				return this._ProveedorID;
			}
			set
			{
				if ((this._ProveedorID != value))
				{
					if (this._Proveedores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProveedorIDChanging(value);
					this.SendPropertyChanging();
					this._ProveedorID = value;
					this.SendPropertyChanged("ProveedorID");
					this.OnProveedorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonedaID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public int MonedaID
		{
			get
			{
				return this._MonedaID;
			}
			set
			{
				if ((this._MonedaID != value))
				{
					if (this._Monedas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMonedaIDChanging(value);
					this.SendPropertyChanging();
					this._MonedaID = value;
					this.SendPropertyChanged("MonedaID");
					this.OnMonedaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraCreacion", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<System.DateTime> FechaHoraCreacion
		{
			get
			{
				return this._FechaHoraCreacion;
			}
			set
			{
				if ((this._FechaHoraCreacion != value))
				{
					this.OnFechaHoraCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraCreacion = value;
					this.SendPropertyChanged("FechaHoraCreacion");
					this.OnFechaHoraCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraModificacion", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<System.DateTime> FechaHoraModificacion
		{
			get
			{
				return this._FechaHoraModificacion;
			}
			set
			{
				if ((this._FechaHoraModificacion != value))
				{
					this.OnFechaHoraModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraModificacion = value;
					this.SendPropertyChanged("FechaHoraModificacion");
					this.OnFechaHoraModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="UniqueIdentifier NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Guid UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Monedas_Doctos", Storage="_Monedas", ThisKey="MonedaID", OtherKey="MonedaID", IsForeignKey=true)]
		public Monedas Monedas
		{
			get
			{
				return this._Monedas.Entity;
			}
			set
			{
				Monedas previousValue = this._Monedas.Entity;
				if (((previousValue != value) 
							|| (this._Monedas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Monedas.Entity = null;
						previousValue.Doctos.Remove(this);
					}
					this._Monedas.Entity = value;
					if ((value != null))
					{
						value.Doctos.Add(this);
						this._MonedaID = value.MonedaID;
					}
					else
					{
						this._MonedaID = default(int);
					}
					this.SendPropertyChanged("Monedas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedores_Doctos", Storage="_Proveedores", ThisKey="ProveedorID", OtherKey="ProveedorID", IsForeignKey=true)]
		public Proveedores Proveedores
		{
			get
			{
				return this._Proveedores.Entity;
			}
			set
			{
				Proveedores previousValue = this._Proveedores.Entity;
				if (((previousValue != value) 
							|| (this._Proveedores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proveedores.Entity = null;
						previousValue.Doctos.Remove(this);
					}
					this._Proveedores.Entity = value;
					if ((value != null))
					{
						value.Doctos.Add(this);
						this._ProveedorID = value.ProveedorID;
					}
					else
					{
						this._ProveedorID = default(int);
					}
					this.SendPropertyChanged("Proveedores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._Monedas = default(EntityRef<Monedas>);
			this._Proveedores = default(EntityRef<Proveedores>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Monedas")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Monedas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MonedaID;
		
		private string _Nombre;
		
		private string _TextoImpteLetra;
		
		private string _Simbolo;
		
		private System.Nullable<System.DateTime> _FechaHoraCreacion;
		
		private System.Nullable<System.DateTime> _FechaHoraModificacion;
		
		private EntitySet<Doctos> _Doctos;
		
		private bool serializing;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMonedaIDChanging(int value);
    partial void OnMonedaIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnTextoImpteLetraChanging(string value);
    partial void OnTextoImpteLetraChanged();
    partial void OnSimboloChanging(string value);
    partial void OnSimboloChanged();
    partial void OnFechaHoraCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraCreacionChanged();
    partial void OnFechaHoraModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraModificacionChanged();
    #endregion
		
		public Monedas()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonedaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int MonedaID
		{
			get
			{
				return this._MonedaID;
			}
			set
			{
				if ((this._MonedaID != value))
				{
					this.OnMonedaIDChanging(value);
					this.SendPropertyChanging();
					this._MonedaID = value;
					this.SendPropertyChanged("MonedaID");
					this.OnMonedaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextoImpteLetra", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string TextoImpteLetra
		{
			get
			{
				return this._TextoImpteLetra;
			}
			set
			{
				if ((this._TextoImpteLetra != value))
				{
					this.OnTextoImpteLetraChanging(value);
					this.SendPropertyChanging();
					this._TextoImpteLetra = value;
					this.SendPropertyChanged("TextoImpteLetra");
					this.OnTextoImpteLetraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Simbolo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Simbolo
		{
			get
			{
				return this._Simbolo;
			}
			set
			{
				if ((this._Simbolo != value))
				{
					this.OnSimboloChanging(value);
					this.SendPropertyChanging();
					this._Simbolo = value;
					this.SendPropertyChanged("Simbolo");
					this.OnSimboloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraCreacion", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<System.DateTime> FechaHoraCreacion
		{
			get
			{
				return this._FechaHoraCreacion;
			}
			set
			{
				if ((this._FechaHoraCreacion != value))
				{
					this.OnFechaHoraCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraCreacion = value;
					this.SendPropertyChanged("FechaHoraCreacion");
					this.OnFechaHoraCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraModificacion", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<System.DateTime> FechaHoraModificacion
		{
			get
			{
				return this._FechaHoraModificacion;
			}
			set
			{
				if ((this._FechaHoraModificacion != value))
				{
					this.OnFechaHoraModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraModificacion = value;
					this.SendPropertyChanged("FechaHoraModificacion");
					this.OnFechaHoraModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Monedas_Doctos", Storage="_Doctos", ThisKey="MonedaID", OtherKey="MonedaID")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7, EmitDefaultValue=false)]
		public EntitySet<Doctos> Doctos
		{
			get
			{
				if ((this.serializing 
							&& (this._Doctos.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Doctos;
			}
			set
			{
				this._Doctos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Doctos(Doctos entity)
		{
			this.SendPropertyChanging();
			entity.Monedas = this;
		}
		
		private void detach_Doctos(Doctos entity)
		{
			this.SendPropertyChanging();
			entity.Monedas = null;
		}
		
		private void Initialize()
		{
			this._Doctos = new EntitySet<Doctos>(new Action<Doctos>(this.attach_Doctos), new Action<Doctos>(this.detach_Doctos));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proveedores")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Proveedores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProveedorID;
		
		private string _Nombre;
		
		private System.Nullable<System.DateTime> _FechaHoraCreacion;
		
		private System.Nullable<System.DateTime> _FechaHoraModificacion;
		
		private EntitySet<Doctos> _Doctos;
		
		private bool serializing;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProveedorIDChanging(int value);
    partial void OnProveedorIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaHoraCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraCreacionChanged();
    partial void OnFechaHoraModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraModificacionChanged();
    #endregion
		
		public Proveedores()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProveedorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ProveedorID
		{
			get
			{
				return this._ProveedorID;
			}
			set
			{
				if ((this._ProveedorID != value))
				{
					this.OnProveedorIDChanging(value);
					this.SendPropertyChanging();
					this._ProveedorID = value;
					this.SendPropertyChanged("ProveedorID");
					this.OnProveedorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraCreacion", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<System.DateTime> FechaHoraCreacion
		{
			get
			{
				return this._FechaHoraCreacion;
			}
			set
			{
				if ((this._FechaHoraCreacion != value))
				{
					this.OnFechaHoraCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraCreacion = value;
					this.SendPropertyChanged("FechaHoraCreacion");
					this.OnFechaHoraCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraModificacion", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<System.DateTime> FechaHoraModificacion
		{
			get
			{
				return this._FechaHoraModificacion;
			}
			set
			{
				if ((this._FechaHoraModificacion != value))
				{
					this.OnFechaHoraModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraModificacion = value;
					this.SendPropertyChanged("FechaHoraModificacion");
					this.OnFechaHoraModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedores_Doctos", Storage="_Doctos", ThisKey="ProveedorID", OtherKey="ProveedorID")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5, EmitDefaultValue=false)]
		public EntitySet<Doctos> Doctos
		{
			get
			{
				if ((this.serializing 
							&& (this._Doctos.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Doctos;
			}
			set
			{
				this._Doctos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Doctos(Doctos entity)
		{
			this.SendPropertyChanging();
			entity.Proveedores = this;
		}
		
		private void detach_Doctos(Doctos entity)
		{
			this.SendPropertyChanging();
			entity.Proveedores = null;
		}
		
		private void Initialize()
		{
			this._Doctos = new EntitySet<Doctos>(new Action<Doctos>(this.attach_Doctos), new Action<Doctos>(this.detach_Doctos));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
}
#pragma warning restore 1591
